baseURL = "http://antidolor.lviv.ua/"
languageCode = "ua"
title = "Позбавлення від болю"
theme = "hugo-initio"
publishDir = "docs"

# Pagination
paginate =5



[blackfriday]
  angledQuotes = true
  fractions = false

[params]
    name = "Позбавлення від болю"
    description = "Фізіотерапевтичний кабінет. Лікування болю. Ударно-хвильова терапія"
    email = "antidolor.lviv@gmail.com"
    phone = "+38 (068) 878-70-74"
	phone_link="+38-068-878-70-74"
	phone2 = "+38 (098) 868-40-60"
	phone_link2="+38-098-868-40-60"
	phone3 = "+38(032) 295-55-95"
	phone_link3 = "+38-032-295-55-95"
    address = "Львів, вул. Наукова, 12а (медичний центр Істина)"
    year = 2018
    background = ""
    favicon = "images/gt_favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = true
    showServices = true
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = true
    footerEnableFormWidget = true

[[menu.main]]
    name = "головна"
    url = "/"
    weight = 1
[[menu.main]]
    name = "статті"
    url = "/post/"
    weight = 5

[params.disqus]
    site = ""

[params.sharethis]
    property = ""
    custom = false

[params.google.analytics]
    trackerID = ""

[[params.social]]
	title = "Сюжет на YouTube каналі Формула Здоров'я"
	url = "https://youtu.be/6BDKVrv2g3o?t=90"
    icon = "fa-youtube-square"
    footer = true
    sharethis = true
    network = "youtube"
[[params.social]]
	title = "email"
	url = "mailto:antidolor.lviv@gmail.com"
    icon = "fa-envelope"
    footer = false
    sharethis = true
    network = "email"